INSERT INTO T_USER(LOGIN, PASSWORD, CREATION_DATE) VALUES
('iwo', '123', CURRENT_TIMESTAMP);

INSERT INTO T_AUTHORITIES(LOGIN, ROLE, ENABLED) VALUES
('iwo', 'COMPANY', true),
('iwo', 'ADMIN', true);

INSERT INTO T_JOB_OFFER(TITLE, JOB_CATEGORY, VALID_FROM, VALID_TO, EMPLOYER_NAME, OWNER_ID)
SELECT 'Job for waiter', 'FOOD_AND_DRINKS', CURRENT_DATE, DATEADD('DAY', 14, CURRENT_DATE), 'Ritz restaurant', ID FROM T_USER WHERE LOGIN='iwo';